device:
  name: NUCLEO-U545RE-Q
  cpu: cortex-m33
  fpu: fpv5-sp-d16
  float_abi: hard
build:
  main_source: main_ai.c
  quantization: INT8
  build_type: Release
paths:
  models_dir: ../stm32_ai_models
  ai_dir: AI
current_model: model_conv2d_standard_c16_d5_PerChannel_quant_random_1.onnx-NUCLEO-U545RE-Q-code_INT8
