device:
  name: NUCLEO-U545RE-Q
  cpu: cortex-m33
  fpu: fpv5-sp-d16
  float_abi: hard
build:
  main_source: main_ai.c
  quantization: F32
  build_type: Debug
paths:
  models_dir: ../stm32_ai_models
  ai_dir: AI
current_model: model_simple_lin_1.onnx-NUCLEO-U545RE-Q-code_F32
